name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: swift test -v

  build:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
